openapi: 3.0.0
info:
  title: ГТО
  description: Документация api запросов для ГТО ПС
  version: 0.0.1

servers:
  - url: https://gtops.herokuapp.com/

paths:
  /api/participant/trial:
    get:
      tags:
        - запросы для рассчета результатов
      summary:
        получение данных об объекте соревнования
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/entities/data'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/entities/TrialData'
        '404':
          $ref: '#/responses/NotFound'
        '400':
          $ref: '#/responses/BadRequest'
        '401':
          $ref: '#/responses/Unauthorized'
        '5XX':
          $ref: '#/responses/Unexpected'

  /api/calculate:
    get:
      tags:
        - запросы для рассчета результатов
      summary:
        получение вторичного результата
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/entities/DataToCalculate'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/entities/ResponseSecondaryResult'
        '404':
          $ref: '#/responses/NotFound'
        '400':
          $ref: '#/responses/BadRequest'
        '401':
          $ref: '#/responses/Unauthorized'
        '5XX':
          $ref: '#/responses/Unexpected'


responses:
  NotFound:
    description: Указанный ресурс не найден
    content:
      application/json:
        schema:
          $ref: '#/responses/Error'
  Unauthorized:
    description: Не авторизованный
    content:
      application/json:
        schema:
          $ref: '#/responses/Error'
  Unexpected:
    description: Ошибка сервера
    content:
      application/json:
        schema:
          $ref: '#/responses/Error'
  BadRequest:
    description: Проверьте запрос отправленный серверу
    content:
      application/json:
        schema:
          $ref: '#/responses/Error'
  Error:
    type: object
    properties:
      code:
        type: number
      status:
        type: number
      title:
        type: string
    required:
      - code
      - title
      - status

entities:
  ResponseSecondaryResult:
    type: object
    properties:
      secondary_result:
        type: number
      primary_result:
        type: number

  TrialData:
    type: object
    properties:
      age_category_id:
        type: number
      count_all_trials:
        type: number
      count_trial_for_gold:
        type: number
      count_trial_for_silver:
        type: number
      count_trial_for_bronze:
        type: number
      trials:
        $ref: '#/entities/DataToTrial'

  DataToTrial:
    type: object
    properties:
      trial_group:
        $ref: '#/entities/DataInGroupOfTrial'

  DataInGroupOfTrial:
    type: object
    properties:
      trial_id:
        type: number
      name_of_trial:
        type: string
      result_for_gold:
        type: number
      result_for_silver:
        type: number
      result_for_bronze:
        type: number
      is_main_trial:
        type: boolean

  DataToCalculate:
    type: object
    properties:
      trial_id:
        type: number
      gender_id:
        type: number
      age_category_id:
        type: number
      primary_result:
        type: number
      required:
        - trial_id
        - gender_id
        - age_category_id
        - primary_result
  data:
    type: object
    properties:
      gender_id:
        type: number
      old:
        type: number
      required:
        - gender_id
        - old
